(defsystem mgasys
  (:pathname-default "/u/deb/mgalisp")
  (:module aux   "AUX.LISP")
  (:module decode "DECODE.LISP")
  (:module mga  "MGA.LISP")
  (:module objfunc  "OBJFUNC.LISP")
  (:module ops "OPS.LISP")
  (:module setup "SETUP.LISP")
  (:module stats  "STATS.LISP")
  (:compile-load mga)
  (:compile-load aux)
  (:compile-load ops)
  (:compile-load setup)
  (:compile-load stats)
  (:compile-load decode)
  (:compile-load objfunc))
