(require "xlisp")
(require "sapa-package")
(require "utilities")
(require "basic-math")
(require "matrix")
(require "basic-statistics")
(require "dft-and-fft")
(require "tapers")
(require "filtering")
(require "random")
(require "acvs")
(require "parametric")
(require "nonparametric")
(require "multitaper")
(require "harmonic")

(use-package :sapa)
