(defun regress-ab (x y)
"simple regression"
 (let* ((mx (mean x))
	(my (mean y))
	(n (length x))
	(b (/
	    (sum (* (- y my) (- x mx)))
	    (sum (* (- x mx) (- x mx)))
	   )
	)
	(a (- my (* b mx)))
	(yhat (+ a (* b x)))
	(resid (- y yhat))
	(ss-res (sum (^ resid 2)))
	(ss-reg (sum (^ (- yhat my) 2)))
	(ss-tot (sum (^ (- y my) 2)))
       )
       (list (list a b) yhat resid (list ss-reg ss-res ss-tot) (list 1 (- n 2) (- n 1)))
 )
)
