   (def node (make-list 5))
   (def level-list'(0 1 1 2 2))
   (def children-list (list '(1 2) nil '(3 4) nil nil))
   (def terminal-list '(nil t nil t t))
 
  (dotimes (i 5)
;(print (nth i node))
(print (nth i level-list))
(print (nth i children-list))
(print (nth i terminal-list))
(print '***)

           (setf (nth i node) (phd-class-model (nth i level-list) 
                      (nth i children-list) (nth i terminal-list)))
           )
